"""
Tests for the models in the ``auth`` application.
"""
import pytest

from auth.domain.models import Role, User


class TestModels:

    def test_user_needs_valid_email(self):
        """Test that a user needs a valid email format."""
        with pytest.raises(ValueError):
            User(
                id="1",
                username="test",
                email="test",
                password="test",
                first_name="test",
                last_name="test",
                profile_picture="test",
                is_active=True,
                role=Role.USER,
            )

    def test_user_needs_valid_role(self):
        """Test that a user needs a valid role."""
        with pytest.raises(ValueError):
            User(
                id="1",
                username="test",
                email="aValid@email.com",
                password="test",
                first_name="test",
                last_name="test",
                profile_picture="test",
                is_active=True,
                role="invalid",
            )

    def test_user_username_is_always_lowercase(self):
        """Test that a user needs a valid username."""
        # given
        username = "TEST"

        # when
        user = User(username=username, email="valid@mail.com", password="test")

        # then
        assert user.username == username.upper().lower()

    def test_user_has_no_whitespace(self):
        """Test that a user has no whitespace."""
        # given
        username = "test "
        password = "   test  "

        # when
        user = User(username=username, email="valid@email.com", password=password)

        # then
        assert user.username == username.strip()
        assert user.password == password.strip()

    def test_user_has_autogenerated_id(self):
        """Test that a user has an autogenerated id."""
        # when
        user = User(username="test", email="valid@email.com", password="test")

        # then
        assert user.id is not None
